name: upper-build

on:
    push:
        paths:
        - ".github/workflows/upper-build.yml"
        - "upper/**"
    workflow_dispatch: # manual

jobs:
    build:
        name: build-dotnet-upper
        runs-on: ubuntu-latest
        steps:
            - run: go version
       